version: '3.8'

services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    network_mode: "host"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm start -- --host 0.0.0.0 --poll 500

  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    network_mode: "host"
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  db-dev:
    image: postgres:15-alpine
    network_mode: "host"
    environment:
      - POSTGRES_DB=notices_board
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev: